export const genresMock = [
  { id: '663b9e7c778b9832cbb97517', title: 'Animation', movieIds: [] },
  { id: '663b9e8e778b9832cbb97521', title: 'Comedy', movieIds: [] },
  { id: '663cdda8b878bb3cf5be71f3', title: 'Crime', movieIds: [] },
  {
    id: '663cddb0b878bb3cf5be71f7',
    title: 'Documentary',
    movieIds: [],
  },
  { id: '663cddb9b878bb3cf5be71fb', title: 'Drama', movieIds: [] },
  { id: '663cddbfb878bb3cf5be71ff', title: 'Family', movieIds: [] },
  { id: '663cddc8b878bb3cf5be7203', title: 'Fantasy', movieIds: [] },
  { id: '663cddd4b878bb3cf5be720b', title: 'History', movieIds: [] },
  {
    id: '663cdddfb878bb3cf5be720f',
    title: 'Horror',
    movieIds: ['663cde89b878bb3cf5be723a'],
  },
  { id: '663cdde4b878bb3cf5be7213', title: 'Music', movieIds: [] },
  { id: '663cddecb878bb3cf5be7217', title: 'Mystery', movieIds: [] },
  { id: '663cddf3b878bb3cf5be721b', title: 'Romance', movieIds: [] },
  {
    id: '663cddfab878bb3cf5be721f',
    title: 'Science Fiction',
    movieIds: ['663cde89b878bb3cf5be723a', '663ce04bb878bb3cf5be7264'],
  },
  { id: '663cde02b878bb3cf5be7223', title: 'TV Movie', movieIds: [] },
  { id: '663cde0ab878bb3cf5be7227', title: 'Thriller', movieIds: [] },
  { id: '663cde1db878bb3cf5be722e', title: 'War', movieIds: [] },
  { id: '663cde23b878bb3cf5be7232', title: 'Western', movieIds: [] },
  {
    id: '663cdfb5b878bb3cf5be7250',
    title: 'Action',
    movieIds: ['663cde89b878bb3cf5be723a', '663ce04bb878bb3cf5be7264'],
  },
  {
    id: '663ce0b6b878bb3cf5be7272',
    title: 'Adventure',
    movieIds: ['663ce04bb878bb3cf5be7264'],
  },
];

export const companiesMock = [
  {
    id: '663cdfe3b878bb3cf5be725b',
    image: '/iDw9Xxok1d9WAM2zFicI8p3khTH.png',
    title: 'TOHO',
    movieIds: ['663cde89b878bb3cf5be723a'],
  },
  {
    id: '663cdff3b878bb3cf5be725f',
    image: '/oxvw2Mrq3GcTxFc2mlT7E5tpek7.png',
    title: 'Robot Communications',
    movieIds: ['663cde89b878bb3cf5be723a'],
  },
  {
    id: 127928,
    image: '/h0rjX5vjW5r8yEnUBStFarjcLT4.png',
    title: '20th Century Studios',
    origin_country: 'US',
  },
  {
    id: 133024,
    image: null,
    title: 'Oddball Entertainment',
    origin_country: 'US',
  },
  {
    id: 89254,
    image: null,
    title: 'Jason T. Reed Productions',
    origin_country: 'US',
  },
  {
    id: 84042,
    image: '/hbln3zGw1R6mkfRETOaUbRuAJSI.png',
    title: 'Ghost Corps',
    origin_country: 'US',
  },
  {
    id: 5,
    image: '/71BqEFAF4V3qjjMPCpLuyJFB9A.png',
    title: 'Columbia Pictures',
    origin_country: 'US',
  },
  {
    id: 130448,
    image: '/yHWTTGKbOGZKUd1cp6l3uLyDeiv.png',
    title: 'Project X Entertainment',
    origin_country: 'US',
  },
  {
    id: 126588,
    image: '/cNhOITS96oOV7SCgUHxvZlWRecx.png',
    title: 'Radio Silence',
    origin_country: 'US',
  },
  {
    id: 33,
    image: '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
    title: 'Universal Pictures',
    origin_country: 'US',
  },
  {
    id: 19367,
    image: null,
    title: 'Vinson Films',
    origin_country: 'US',
  },
  {
    id: 1311,
    image: '/ic2bTizdzRLDVzAvN7MXdUg3WQV.png',
    title: 'The Asylum',
    origin_country: 'US',
  },
  {
    id: 152189,
    image: null,
    title: 'The Global Asylum, LLC.',
    origin_country: '',
  },
  {
    id: 521,
    image: '/kP7t6RwGz2AvvTkvnI1uteEwHet.png',
    title: 'DreamWorks Animation',
    origin_country: 'US',
  },
  {
    id: 114152,
    image: '/xYfrnGFXxrEy5x5OVThunxHYScK.png',
    title: 'The Stone Quarry',
    origin_country: 'US',
  },
  {
    id: 156880,
    image: null,
    title: 'Grand Electric',
    origin_country: 'US',
  },
  {
    id: 9996,
    image: '/3tvBqYsBhxWeHlu62SIJ1el93O7.png',
    title: 'Syncopy',
    origin_country: 'GB',
  },
  {
    id: 507,
    image: '/aRmHe6GWxYMRCQljF75rn2B9Gv8.png',
    title: 'Atlas Entertainment',
    origin_country: 'US',
  },
  {
    id: 1225,
    image: '/rIxhJMR7oK8b2fMakmTfRLY2TZv.png',
    title: 'One Race',
    origin_country: 'US',
  },
  {
    id: 34530,
    image: null,
    title: 'Perfect Storm Entertainment',
    origin_country: 'US',
  },
  {
    id: 101405,
    image: null,
    title: '6th & Idaho',
    origin_country: 'US',
  },
  {
    id: 119245,
    image: '/6F45uVsKpNYANcWvplyhgIFezFU.png',
    title: 'Dylan Clark Productions',
    origin_country: 'US',
  },
  {
    id: 128064,
    image: '/13F3Jf7EFAcREU0xzZqJnVnyGXu.png',
    title: 'DC Films',
    origin_country: 'US',
  },
  {
    id: 174,
    image: '/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png',
    title: 'Warner Bros. Pictures',
    origin_country: 'US',
  },
];

export const moviesMock = [
  {
    title: 'Godzilla Minus One',
    description:
      'Postwar Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb.',
    image: '/2E2WTX0TJEflAged6kzErwqX1kt.jpg',
    voteAverange: '7.748',
    voteCount: '837',
    trailer: 'CEArEbO25lE',
    budget: '15000000',
    releaseDate: '2023-11-03T00:00:00.000Z',
    revenue: '115857413',
    duration: '125',
  },
  {
    title: 'Godzilla x Kong: The New Empire',
    description:
      'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.',
    image: '/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg',
    voteAverange: '6.472',
    voteCount: '988',
    trailer: '3N84gAPPKXE',
    budget: '150000000',
    releaseDate: '2024-03-27T00:00:00.000Z',
    revenue: '546503756',
    duration: '115',
  },
  {
    title: 'Kingdom of the Planet of the Apes',
    description:
      "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
    image: '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
    voteAverange: '7.304',
    voteCount: '321',
    trailer: '1kSAnG_e_-M',
    budget: '100000000',
    releaseDate: '2024-05-08T00:00:00.000Z',
    revenue: '129000000',
    duration: '145',
  },
  {
    title: 'Ghostbusters: Frozen Empire',
    description:
      'After the original team developed a top-secret research laboratory to take the shattered ghosts to the next level. But when the discovery of an ancient artifact unleashes an evil force, both new and old must join forces to protect their homeland and save the world from the Second Ice Age... from the very thing that unleashes an unstoppable force from the depths of history. As chaos reigns and pure evil plunges the world into darkness, the Ghostbusters must step forward once again to save humanity from the brink of doom. With two generations of Ghostbusters fighting side by side, the stakes have never been higher. Will they be able to avert the inevitable before everything freezes?',
    image: '/e1J2oNzSBdou01sUvriVuoYp0pJ.jpg',
    voteAverange: '6.734',
    voteCount: '691',
    trailer: 'ARqGaZNg08Y',
    budget: '15000000',
    releaseDate: '2024-03-20T00:00:00.000Z',
    revenue: '195741452',
    duration: '115',
  },
  {
    title: 'Abigail',
    description:
      'A group of criminals kidnaps a teenage ballet dancer, the daughter of a notorious gang leader, in order to obtain a ransom of $50 million, but over time, they discover that she is not just an ordinary girl. After the kidnappers begin to diminish, one by one, they discover, to their increasing horror, that they are locked inside with an unusual girl.',
    image: '/7qxG0zyt29BI0IzFDfsps62kbQi.jpg',
    voteAverange: '7',
    voteCount: '352',
    trailer: 'S6BPb9PQqCk',
    budget: '28000000',
    releaseDate: '2024-03-27T00:00:00.000Z',
    revenue: '37546000',
    duration: '109',
  },
  {
    title: 'Ape vs. Mecha Ape',
    description:
      'Recognizing the destructive power of its captive giant Ape, the military makes its own battle-ready A.I., Mecha Ape. But its first practical test goes horribly wrong, leaving the military no choice but to release the imprisoned giant ape to stop the colossal robot before it destroys downtown Chicago.',
    image: '/dJaIw8OgACelojyV6YuVsOhtTLO.jpg',
    voteAverange: '5.573',
    voteCount: '164',
    trailer: 'dtyPh5yCoWg',
    budget: '0',
    releaseDate: '2023-03-24T00:00:00.000Z',
    revenue: '0',
    duration: '80',
  },
  {
    title: 'Kung Fu Panda 4',
    description:
      'Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.',
    image: '/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg',
    voteAverange: '7.13',
    voteCount: '1631',
    trailer: 'z8KyhxCZSog',
    budget: '85000000',
    releaseDate: '2024-03-02T00:00:00.000Z',
    revenue: '520540090',
    duration: '94',
  },
  {
    title: 'Rebel Moon - Part Two: The Scargiver',
    description:
      'The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.',
    image: '/cxevDYdeFkiixRShbObdwAHBZry.jpg',
    voteAverange: '6.093',
    voteCount: '744',
    trailer: 'UEJuNHOd8Dw',
    budget: '83000000',
    releaseDate: '2024-04-19T00:00:00.000Z',
    revenue: '0',
    duration: '123',
  },
  {
    title: 'Oppenheimer',
    description:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    image: '/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg',
    voteAverange: '8.102',
    voteCount: '8010',
    trailer: 'O_hKC3gRvzw',
    budget: '100000000',
    releaseDate: '2023-07-19T00:00:00.000Z',
    revenue: '952000000',
    duration: '181',
  },
  {
    title: 'Fast X',
    description:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever..",
    image: '/fiVW06jE7z9YnO4trhaMEdclSiC.jpg',
    voteAverange: '7.123',
    voteCount: '5150',
    trailer: '0qCCiY2se90',
    budget: '340000000',
    releaseDate: '2023-05-17T00:00:00.000Z',
    revenue: '704709660',
    duration: '142',
  },
  {
    title: 'The Batman',
    description:
      'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
    image: '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    voteAverange: '7.679',
    voteCount: '9562',
    trailer: 'xayUJkfIcpA',
    budget: '185000000',
    releaseDate: '2022-03-01T00:00:00.000Z',
    revenue: '771000000',
    duration: '177',
  },
];

export const currentUserId = '6646326912012c586783a572';
